// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class CloudSaveSdkBindings
    {
        readonly ICloudCodeService k_Service;
        public CloudSaveSdkBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SaveValue(string key, string value)
        {
            await k_Service.CallModuleEndpointAsync(
                "CloudSaveModule",
                "SaveValue",
                new Dictionary<string, object>()
                {
                    {"key", key},
                    {"value", value},
                });
        }

        public async Task<Dictionary<string,int>> GetInventory()
        {
            return await k_Service.CallModuleEndpointAsync<Dictionary<string,int>>(
                "CloudSaveModule",
                "GetInventory",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
