// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class QuestControllerBindings
    {
        readonly ICloudCodeService k_Service;
        public QuestControllerBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> AssignQuest()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "QuestSystem",
                "AssignQuest",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> GetQuestStatus()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "QuestSystem",
                "GetQuestStatus",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
